apiVersion: v1
kind: Service
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
spec:
  type: ClusterIP
  selector:
    app: employee-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
